apiVersion: v1
kind: Pod
metadata:
  name: test-layer2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: dpdk-net
spec:
  containers:
    - name: test
      image: nicolaka/netshoot:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: pci-info
          mountPath: /var/run/netdev-cni
  volumes:
    - name: pci-info
      hostPath:
        path: /var/run/netdev-cni
