apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netdev-cni-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: netdev-cni-agent
  template:
    metadata:
      labels:
        app: netdev-cni-agent
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: install-cni
          image: localhost/netdev-cni/cni-plugin:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "cp /netdev-cni /opt/cni/bin/netdev-cni"]
          volumeMounts:
            - name: cni-bin
              mountPath: /opt/cni/bin
      containers:
        - name: agent
          image: localhost/netdev-cni/node-agent:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: agent-sock
              mountPath: /var/run/netdev-cni
            - name: sys
              mountPath: /sys
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: agent-sock
          hostPath:
            path: /var/run/netdev-cni
            type: DirectoryOrCreate
        - name: sys
          hostPath:
            path: /sys
